# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Teapot_config = debug
  TeapotApp_config = debug
  GLFW_config = debug
  GLAD_config = debug
  ImGui_config = debug

else ifeq ($(config),release)
  Teapot_config = release
  TeapotApp_config = release
  GLFW_config = release
  GLAD_config = release
  ImGui_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Teapot TeapotApp GLFW GLAD ImGui

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Teapot: GLFW GLAD ImGui
ifneq (,$(Teapot_config))
	@echo "==== Building Teapot ($(Teapot_config)) ===="
	@${MAKE} --no-print-directory -C Teapot -f Makefile config=$(Teapot_config)
endif

TeapotApp: Teapot GLFW GLAD ImGui
ifneq (,$(TeapotApp_config))
	@echo "==== Building TeapotApp ($(TeapotApp_config)) ===="
	@${MAKE} --no-print-directory -C TeapotApp -f Makefile config=$(TeapotApp_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Teapot/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Teapot/vendor/GLAD -f Makefile config=$(GLAD_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Teapot/vendor/ImGui -f Makefile config=$(ImGui_config)
endif

clean:
	@${MAKE} --no-print-directory -C Teapot -f Makefile clean
	@${MAKE} --no-print-directory -C TeapotApp -f Makefile clean
	@${MAKE} --no-print-directory -C Teapot/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Teapot/vendor/GLAD -f Makefile clean
	@${MAKE} --no-print-directory -C Teapot/vendor/ImGui -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Teapot"
	@echo "   TeapotApp"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   ImGui"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"