#pragma once

#define TEA_MOUSE_MIDDLE           2

#define TEA_KEY_SPACE              32
#define TEA_KEY_APOSTROPHE         39  
#define TEA_KEY_COMMA              44  
#define TEA_KEY_MINUS              45  
#define TEA_KEY_PERIOD             46  
#define TEA_KEY_SLASH              47  
#define TEA_KEY_0                  48
#define TEA_KEY_1                  49
#define TEA_KEY_2                  50
#define TEA_KEY_3                  51
#define TEA_KEY_4                  52
#define TEA_KEY_5                  53
#define TEA_KEY_6                  54
#define TEA_KEY_7                  55
#define TEA_KEY_8                  56
#define TEA_KEY_9                  57
#define TEA_KEY_SEMICOLON          59  
#define TEA_KEY_EQUAL              61  
#define TEA_KEY_A                  65
#define TEA_KEY_B                  66
#define TEA_KEY_C                  67
#define TEA_KEY_D                  68
#define TEA_KEY_E                  69
#define TEA_KEY_F                  70
#define TEA_KEY_G                  71
#define TEA_KEY_H                  72
#define TEA_KEY_I                  73
#define TEA_KEY_J                  74
#define TEA_KEY_K                  75
#define TEA_KEY_L                  76
#define TEA_KEY_M                  77
#define TEA_KEY_N                  78
#define TEA_KEY_O                  79
#define TEA_KEY_P                  80
#define TEA_KEY_Q                  81
#define TEA_KEY_R                  82
#define TEA_KEY_S                  83
#define TEA_KEY_T                  84
#define TEA_KEY_U                  85
#define TEA_KEY_V                  86
#define TEA_KEY_W                  87
#define TEA_KEY_X                  88
#define TEA_KEY_Y                  89
#define TEA_KEY_Z                  90
#define TEA_KEY_LEFT_BRACKET       91  
#define TEA_KEY_BACKSLASH          92  
#define TEA_KEY_RIGHT_BRACKET      93  
#define TEA_KEY_GRAVE_ACCENT       96  